
export const database = ([
    {
        id: 1,
        name: '4cite Non-qualified email series',
        status: 'backlog',
        x: '',
        y: '',
        height: '',
        dueDate: '',
        dateCreated: '',
        dateCompleted: '',
        timeTaken: '',
        priority: ''
    },
    {
        id: 2,
        name: 'BND Mailings - Trigger Email Campaigns',
        status: 'backlog',
        x: '',
        y: '',
        height: '',
        dueDate: '',
        dateCreated: '',
        dateCompleted: '',
        timeTaken: '',
        priority: ''
    },
    {
        id: 3,
        name: "Dec '22 :: Requal Trigger Updates - Never Qual",
        status: 'backlog',
        x: '',
        y: '',
        height: '',
        dueDate: '',
        dateCreated: '',
        dateCompleted: '',
        timeTaken: '',
        priority: ''
    },
    {
        id: 4,
        name: 'Swap products for 0-12',
        status: 'To do',
        x: '',
        y: '',
        height: '',
        dueDate: '',
        dateCreated: '',
        dateCompleted: '',
        timeTaken: '',
        priority: ''
    },
    {
        id: 5,
        name: 'Updating Allianz pricing and T&C',
        status: 'To do',
        x: '',
        y: '',
        height: '',
        dueDate: '',
        dateCreated: '',
        dateCompleted: '',
        timeTaken: '',
        priority: ''
    },
    {
        id: 6,
        name: 'Email factory v3',
        status: 'inProgress',
        x: '',
        y: '',
        height: '',
        dueDate: '',
        dateCreated: '',
        dateCompleted: '',
        timeTaken: '',
        priority: ''
    },
    {   id: 7,
        name: 'Re activate non risky PTs in SFMC',
        summary: '',
        notes: '20 active , 5 bounced, 994 held, 1 unsubscribed => 1020 active\n332 removed from Master Exclusion List (24,886 - 24,554)',
        status: 'complete',
        x: '',
        y: '',
        height: '',
        dueDate: '2023-03-21T18:00:00',
        dateCreated: '2023-03-21T13:02:20',
        dateCompleted: '2023-03-21T17:04:16',
        timeTaken: '',
        priority: ''
    },
    {
        id: 8,
        name: 'Email testing app',
        status: 'review',
        x: '',
        y: '',
        height: '',
        dueDate: '',
        dateCreated: '2023-03-16T19:30:00',
        dateCompleted: '',
        timeTaken: '',
        priority: ''
    },
    {   id: 9,
        name: 'Run emails through checking tool',
        summary: 'EM83170 03-13 \nEM83190 03-15 \nEM83290 03-17 \nEM83240 03-22 \nEM83380 03-24',
        notes: 'Send to Rick when done',
        status: 'complete',
        x: '',
        y: '',
        height: '',
        dueDate: '2023-03-21T12:00:00',
        dateCreated: '2023-03-21T10:39:00',
        dateCompleted: '2023-03-21T11:41:00',
        timeTaken: '',
        priority: ''
    },
    {   id: 10,
        name: 'Take Out Hyperlink for mid@vantagetravel etc..',
        summary: '',
        notes: '',
        status: 'To do',
        x: '',
        y: '',
        height: '',
        dueDate: '',
        dateCreated: '2023-03-21T16:47:55',
        dateCompleted: '',
        timeTaken: '',
        priority: ''
    }
]);